### ISSUE TITLE
数据度量的共性

### ISSUE THREAD

**Issue by zxh456** [bxiaopeng/SoftwareTestingWeekly#1]
# 数据度量的共性

我们的测试平台上，有各种图表，其实都是有共性的。 从一个例子说起。<br />
<br />**基础数据：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987317386-ab6d794a-44d5-457e-a3be-fa8283d85ef0.png#align=left&display=inline&height=146&margin=%5Bobject%20Object%5D&name=image.png&originHeight=146&originWidth=248&size=8547&status=done&style=none&width=248)<br />**统计一班和二班的人数 (表格)：**
```sql
select 班级, count(*) AS 学生个数 FROM table_student GROUP BY 班级：
```
**图表：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987323968-3a6debb8-c08c-4860-9a5f-c289edbbcd55.png#align=left&display=inline&height=62&margin=%5Bobject%20Object%5D&name=image.png&originHeight=62&originWidth=150&size=2369&status=done&style=none&width=150)<br />**柱状图：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987330000-57144dc9-6d10-4d47-9fb1-16b9a600a7b0.png#align=left&display=inline&height=151&margin=%5Bobject%20Object%5D&name=image.png&originHeight=151&originWidth=223&size=3070&status=done&style=none&width=223)<br />**饼图：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987334888-a89d867d-2f77-407a-ba00-684a34532a40.png#align=left&display=inline&height=183&margin=%5Bobject%20Object%5D&name=image.png&originHeight=183&originWidth=268&size=5050&status=done&style=none&width=268)<br />
<br />**统计每个老师在每个班级中带的学生个数：**
```sql
SELECT 班级，老师，COUNT(*) AS 学生个数 FROM table_student GROUP BY 班级，老师
```
**图表：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987339941-1946894c-afa9-4925-8a68-bef87309af6e.png#align=left&display=inline&height=94&margin=%5Bobject%20Object%5D&name=image.png&originHeight=94&originWidth=222&size=5076&status=done&style=none&width=222)<br />**更进一步的图表：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987348616-2f24c0ae-4684-4a0b-a934-cd5d8c80eeae.png#align=left&display=inline&height=79&margin=%5Bobject%20Object%5D&name=image.png&originHeight=79&originWidth=220&size=3801&status=done&style=none&width=220)<br />**二维柱状图：**<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987363702-6bd77664-2678-4ec1-8727-a5ebcbde5068.png#align=left&display=inline&height=190&margin=%5Bobject%20Object%5D&name=image.png&originHeight=190&originWidth=300&size=6841&status=done&style=none&width=300)<br />**抽象成数据规范：**<br />只要有一份数据，是下面的格式，就可以转换为一份二维表格/柱状图/折线图，而缺少dimension(维度)或者group时，其实就是一份一维表格/柱状图/折线图/饼图。<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1609987379871-c31224b7-7e74-402e-b2e5-8d89cafe9319.png#align=left&display=inline&height=80&margin=%5Bobject%20Object%5D&name=image.png&originHeight=80&originWidth=212&size=2985&status=done&style=none&width=212)<br />因此可以规范所有的后端接口都能得到这样的数据，那么前端就一定可以将其展现成一张图表。
```
[
  {
    dimension : xx,
    group : xx,
    value : xx
  }
 ...
]
```

---

**接口平台里的一维数据：**<br />**<br />**基础数据：**<br />**![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1610004211192-4082178a-4173-4099-955c-eb06c2a754f3.png#align=left&display=inline&height=183&margin=%5Bobject%20Object%5D&name=image.png&originHeight=183&originWidth=524&size=44426&status=done&style=none&width=524)**<br />**统计结果是优良差的个数：**
```sql
SELECT result, sum(count) FROM score_result_project where result in ('优', '良', '差') group by result
```
**![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1610004035598-6388e232-22f2-4ed4-abe2-17723d7dc3a8.png#align=left&display=inline&height=74&margin=%5Bobject%20Object%5D&name=image.png&originHeight=74&originWidth=110&size=3753&status=done&style=none&width=110)<br />**<br />**绘制一维饼图：**<br />**![image.png](https://cdn.nlark.com/yuque/0/2021/png/10387214/1610004139511-d2345c6f-1918-4b77-8aae-26f9b70c831e.png#align=left&display=inline&height=232&margin=%5Bobject%20Object%5D&name=image.png&originHeight=232&originWidth=243&size=8905&status=done&style=none&width=243)**<br />**后端返回数据：**
```json
[
  {
  "value": "4086",
  "name": "差"
  },
  {
  "value": "522",
  "name": "良"
  },
  {
  "value": "23",
  "name": "优"
  }
]
```
**<br />**更精彩的思考请继续：[参考：度量平台开发实践](https://testerhome.com/topics/23466)**<br />**<br />

**Comment by mansucache** [comment]
已收录
